### ISSUE TITLE
Fail to download node-serialport

### ISSUE THREAD

**Issue by DiDongDongDi** [Moki38/Moki-ROV2#1]
Hello! When I want to `./install.sh`, an error occurred 
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@6.11.2 (node-v48 ABI) (falling back to source compile with node-gyp)
the website is 404. 
But I download node-serialport from here
https://github.com/node-serialport/node-serialport/releases
and I put the package in `/root` , installed again, but it didn't work.

And I used the mega2560 instead of teensy, use raspi's usb port connected the mega2560, it displayed
Error opening USB device: No error
Waiting for Teensy device...
(hint: press the reset button)

is there any problem with my connection?
Thank you!

**Comment by Moki38** [comment]
Your first error is a version problem, you have to fix that yourself (as this code is no longer maintained)

The 2nd error, looks like is has to do with the "pio" platform.
This may be the fix: platformio init -b megaatmega2560 (for Arduino Mega2560)

**Comment by DiDongDongDi** [comment]
Thank you for your responding.
